const images = {
    flutter: '/assets/flutter.png',
    redux: '/assets/redux.png',
    sass: '/assets/sass.png',
    email: '/assets/email.png',
    mobile: '/assets/mobile.png',
    api: '/assets/api.png',
    cpp: '/assets/cpp.png',
    css: '/assets/css.png',
    figma: '/assets/figma.png',
    git: '/assets/git.png',
    graphql: '/assets/graphql.png',
    html: '/assets/html.png',
    javascript: '/assets/javascript.png',
    mu5: '/assets/mu5.png',
    node: '/assets/node.png',
    python: '/assets/python.png',
    react: '/assets/react.png',
    typescript: '/assets/typescript.png',
    vue: '/assets/vue.png',
    about01: '/assets/about01.png',
    about02: '/assets/about02.png',
    about03: '/assets/about03.png',
    about04: '/assets/about04.png',
    profil: '/assets/profil.jpg',
    profile: '/assets/profile.png',
    circle: '/assets/circle.svg',
    logo: '/assets/logo.png',
    adidas: '/assets/adidas.png',
    amazon: '/assets/amazon.png',
    asus: '/assets/asus.png',
    bolt: '/assets/bolt.png',
    nb: '/assets/nb.png',
    skype: '/assets/skype.png',
    spotify: '/assets/spotify.png'
}

export default images